Module 3. All task
js-tasks-ru/jsbasic-20201008_redtol pull request #3
Opened 2020-10-22 21:04 UTC by Web-Nic

2020-10-22 22:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Функция showSalary(users, age)
- для пользователей д�� 40 лет должна вывести строку с зарплатами
- для пользователей до 30 лет должна вывести строку с зарплатами
```
```diff
Найти min/max в строке
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
+ 25,-1,-234,4,   1000
```

2020-10-23 09:53 UTC, stas-dolgachov requested changes

2020-10-23 09:53 UTC, stas-dolgachov commented on 3-module/1-task/index.js
> +  return users.map(item => item.name);
👍

2020-10-23 09:53 UTC, stas-dolgachov commented on 3-module/2-task/index.js
> +  return arr.filter( item => item >= a && item <= b);
👍

2020-10-23 09:53 UTC, stas-dolgachov commented on 3-module/4-task/index.js
> +      finalStr += `${arr[i].name}, ${arr[i].balance}\n`;
Эту задачу можно попробовать решить немного иначе. Сделать сначала  map, получить массив строк, а потом сделать `join('\n')`

2020-10-23 09:53 UTC, stas-dolgachov commented on 3-module/4-task/index.js
> +  for (let i = 0; i < arr.length; i++) {
У вас здесь используется неправильное имя переменной, в коде используете `arr`, а параметр называется `users`. 
Поэтому тест не проходят.

2020-10-23 11:01 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Функция showSalary(users, age)
+ для пользователей до 30 лет должна вывести строку с зарплатами
+ для пользователей до 40 лет должна вывести строку с зарплатами
```
```diff
Фильтрация по диапазону
+ не должна менять исходный массив
+ должна фильтровать диапазон
```
```diff
Найти min/max в строке
+ 25,-1,-234,4,   1000
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-10-23 17:03 UTC, stas-dolgachov approved these changes

2020-10-23 17:03 UTC, stas-dolgachov commented on 3-module/5-task/index.js
> +  return {min: +newStr[0], max: +newStr[newStr.length - 1]};
Мне такое решение нравится, вы зря переживаете 👍

2020-10-23 17:03 UTC, merged